name: Docker Build and Push with NVIDIA

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, Linux, X64]
    container:
      image: nvidia/cuda:11.4-base-ubuntu20.04

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Set date tag
        id: date_tag
        run: echo "DATE_TAG=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: bpawnzz/kodi-docker-nvidia:${{ env.DATE_TAG }}
          file: ./Dockerfile.nvidia
          platforms: linux/amd64,linux/arm64
          build-args: |
            KODI_VERSION=19

