name: Dockerfile Build and Push

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Set date tag
        id: date_tag
        run: echo "DATE_TAG=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t bpawnzz/kodi-docker:${{ env.DATE_TAG }} .

      - name: Push Docker image to Docker Hub
        run: |
          docker push bpawnzz/kodi-docker:${{ env.DATE_TAG }}

      - name: Log in to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}  # Using the new GHCR_TOKEN

      - name: Convert repository name to lowercase
        id: lowercase_repository
        run: echo "lowercase_repository=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build Docker image for GitHub Packages
        run: |
          docker build -t ghcr.io/${{ env.lowercase_repository }}/kodi-docker:${{ env.DATE_TAG }} .

      - name: Push Docker image to GitHub Packages
        run: |
          docker push ghcr.io/${{ env.lowercase_repository }}/kodi-docker:${{ env.DATE_TAG }}  # <-- Ensure NO period here
