name: Docker Build and Push with NVIDIA

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, Linux, X64]
    container:
      image: nvidia/cuda:12.3.0-runtime-ubuntu22.04

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Set date tag
        id: date_tag
        run: echo "DATE_TAG=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            bpawnzz/docker-kodi-nvidia:${{ env.DATE_TAG }}
            bpawnzz/docker-kodi-nvidia:latest
          file: ./Dockerfile.nvidia
          platforms: linux/amd64
          build-args: |
            KODI_VERSION=20
