name: Dockerfile.nvidia Build and Push

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -f Dockerfile.nvidia -t bpawnzz/kodi-docker-nvidia:latest .

      - name: Push Docker image to Docker Hub
        run: |
          docker push bpawnzz/kodi-docker-nvidia:latest

      - name: Log in to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image for GitHub Packages
        run: |
          docker build -f Dockerfile.nvidia -t ghcr.io/${{ github.repository }}/kodi-docker-nvidia:latest .

      - name: Push Docker image to GitHub Packages
        run: |
          docker push ghcr.io/${{ github.repository }}/kodi-docker-nvidia:latest
